Mysql:
  enable: false
  hostname: "localhost"
  database: "plugins"
  username: "root"
  password: "teste"
  port: 3306

# Placeholders:
# {nome} - Nome do Jogador
# {numero} - Número do Top
# {saldo} - Quantidade de Cash

Mensagens:
  NotFound: "&cJogador não encontrado em nosso banco de dados."
  IncorrectValue: "&cValor incorreto, por favor insira um valor válido."
  Yourself: "&cVocê não pode enviar coins a si mesmo."
  NoPermission: "&cVocê não tem permissão para executar este comando"
  Cash:
    1: "&eSeu saldo:&f {saldo}"
    2: "&eSaldo de &f{nome} &eé &f{saldo}"
  CashAdd: "&aFoi adicionado a conta de {nome} a quantia de {saldo}"
  CashCriar:
    1: "&aConta {nome} criada com sucesso!"
    2: "&cJá existe uma conta com o nome {nome}!"
  CashDeletar:
    1: "&aConta {nome} deletada com sucesso!"
    2: "&cConta {nome} não encontrada em nosso banco de dados."
  CashEnviar:
    1: "&aVocê enviou {saldo} para {nome}"
    2: "&aVocê acaba de receber {saldo} de {nome}"
    3: "&cVocê não tem cash suficiente para isso."
  CashRemove: "&aFoi removido a quantia de {saldo} da conta de {nome}"
  CashSet: "&aFoi setado a quantia de {saldo} na conta de {nome}"
  CashToggle:
    1: "&aVocê {toggle} seu recibimento de cash"
    2: "&cJogador está com recebimento de cash desativado"
  CashTop:
    Title: "&6&l CASH TOP &7(Atualiza de 5 em 5 minutos)"
    2: "&c  Não existe jogadores cadastrados ainda."
    Settings: "&f{numero}. &e{nome}: &7({saldo})"

Settings:
  # Formato do cash:
  # 0 = 100.000 / 1 = 100k / 2 = 100 mil
  Formato: 1
    